name: mapmytrip
description: Mobile app that let's you share your trip.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 6.0.3
  firebase_core: ^2.4.0

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.9
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^4.2.8
  json_annotation: ^4.8.0
  google_sign_in: ^6.0.0
  google_fonts: ^4.0.3
  rxdart: ^0.27.7
  cloud_firestore: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: ^2.3.3
  json_serializable: ^6.5.4

flutter:
  assets:
    - assets/

  uses-material-design: true
